// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class DocumentoComercial
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject documentoComercialMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.DocumentoComercial";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		id_doc("id_doc"),
		tipoDoccomercial("tipoDoccomercial"),
		numero("numero"),
		link("link"),
		adjunto("adjunto");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DocumentoComercial(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.DocumentoComercial"));
	}

	protected DocumentoComercial(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject documentoComercialMendixObject)
	{
		if (documentoComercialMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.DocumentoComercial", documentoComercialMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.DocumentoComercial");

		this.documentoComercialMendixObject = documentoComercialMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DocumentoComercial.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.DocumentoComercial initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.DocumentoComercial.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.DocumentoComercial initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.DocumentoComercial(context, mendixObject);
	}

	public static myfirstmodule.proxies.DocumentoComercial load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.DocumentoComercial.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.DocumentoComercial> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.DocumentoComercial> result = new java.util.ArrayList<myfirstmodule.proxies.DocumentoComercial>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.DocumentoComercial" + xpathConstraint))
			result.add(myfirstmodule.proxies.DocumentoComercial.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of id_doc
	 */
	public final java.lang.Long getid_doc()
	{
		return getid_doc(getContext());
	}

	/**
	 * @param context
	 * @return value of id_doc
	 */
	public final java.lang.Long getid_doc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.id_doc.toString());
	}

	/**
	 * Set value of id_doc
	 * @param id_doc
	 */
	public final void setid_doc(java.lang.Long id_doc)
	{
		setid_doc(getContext(), id_doc);
	}

	/**
	 * Set value of id_doc
	 * @param context
	 * @param id_doc
	 */
	public final void setid_doc(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long id_doc)
	{
		getMendixObject().setValue(context, MemberNames.id_doc.toString(), id_doc);
	}

	/**
	 * @return value of tipoDoccomercial
	 */
	public final java.lang.String gettipoDoccomercial()
	{
		return gettipoDoccomercial(getContext());
	}

	/**
	 * @param context
	 * @return value of tipoDoccomercial
	 */
	public final java.lang.String gettipoDoccomercial(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.tipoDoccomercial.toString());
	}

	/**
	 * Set value of tipoDoccomercial
	 * @param tipodoccomercial
	 */
	public final void settipoDoccomercial(java.lang.String tipodoccomercial)
	{
		settipoDoccomercial(getContext(), tipodoccomercial);
	}

	/**
	 * Set value of tipoDoccomercial
	 * @param context
	 * @param tipodoccomercial
	 */
	public final void settipoDoccomercial(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tipodoccomercial)
	{
		getMendixObject().setValue(context, MemberNames.tipoDoccomercial.toString(), tipodoccomercial);
	}

	/**
	 * @return value of numero
	 */
	public final java.lang.String getnumero()
	{
		return getnumero(getContext());
	}

	/**
	 * @param context
	 * @return value of numero
	 */
	public final java.lang.String getnumero(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.numero.toString());
	}

	/**
	 * Set value of numero
	 * @param numero
	 */
	public final void setnumero(java.lang.String numero)
	{
		setnumero(getContext(), numero);
	}

	/**
	 * Set value of numero
	 * @param context
	 * @param numero
	 */
	public final void setnumero(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String numero)
	{
		getMendixObject().setValue(context, MemberNames.numero.toString(), numero);
	}

	/**
	 * @return value of link
	 */
	public final java.lang.String getlink()
	{
		return getlink(getContext());
	}

	/**
	 * @param context
	 * @return value of link
	 */
	public final java.lang.String getlink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.link.toString());
	}

	/**
	 * Set value of link
	 * @param link
	 */
	public final void setlink(java.lang.String link)
	{
		setlink(getContext(), link);
	}

	/**
	 * Set value of link
	 * @param context
	 * @param link
	 */
	public final void setlink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String link)
	{
		getMendixObject().setValue(context, MemberNames.link.toString(), link);
	}

	/**
	 * @return value of adjunto
	 */
	public final java.lang.Long getadjunto()
	{
		return getadjunto(getContext());
	}

	/**
	 * @param context
	 * @return value of adjunto
	 */
	public final java.lang.Long getadjunto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.adjunto.toString());
	}

	/**
	 * Set value of adjunto
	 * @param adjunto
	 */
	public final void setadjunto(java.lang.Long adjunto)
	{
		setadjunto(getContext(), adjunto);
	}

	/**
	 * Set value of adjunto
	 * @param context
	 * @param adjunto
	 */
	public final void setadjunto(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long adjunto)
	{
		getMendixObject().setValue(context, MemberNames.adjunto.toString(), adjunto);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return documentoComercialMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.DocumentoComercial that = (myfirstmodule.proxies.DocumentoComercial) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.DocumentoComercial";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
