// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Empresa
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject empresaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Empresa";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		id_empresa("id_empresa"),
		nombre("nombre"),
		personal("personal"),
		actividad("actividad"),
		promDeVentasAnual("promDeVentasAnual"),
		tipoEmpresa("tipoEmpresa");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Empresa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Empresa"));
	}

	protected Empresa(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject empresaMendixObject)
	{
		if (empresaMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Empresa", empresaMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Empresa");

		this.empresaMendixObject = empresaMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Empresa.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Empresa initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Empresa.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Empresa initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Empresa(context, mendixObject);
	}

	public static myfirstmodule.proxies.Empresa load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Empresa.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Empresa> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Empresa> result = new java.util.ArrayList<myfirstmodule.proxies.Empresa>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Empresa" + xpathConstraint))
			result.add(myfirstmodule.proxies.Empresa.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of id_empresa
	 */
	public final java.lang.Long getid_empresa()
	{
		return getid_empresa(getContext());
	}

	/**
	 * @param context
	 * @return value of id_empresa
	 */
	public final java.lang.Long getid_empresa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.id_empresa.toString());
	}

	/**
	 * Set value of id_empresa
	 * @param id_empresa
	 */
	public final void setid_empresa(java.lang.Long id_empresa)
	{
		setid_empresa(getContext(), id_empresa);
	}

	/**
	 * Set value of id_empresa
	 * @param context
	 * @param id_empresa
	 */
	public final void setid_empresa(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long id_empresa)
	{
		getMendixObject().setValue(context, MemberNames.id_empresa.toString(), id_empresa);
	}

	/**
	 * @return value of nombre
	 */
	public final java.lang.String getnombre()
	{
		return getnombre(getContext());
	}

	/**
	 * @param context
	 * @return value of nombre
	 */
	public final java.lang.String getnombre(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nombre.toString());
	}

	/**
	 * Set value of nombre
	 * @param nombre
	 */
	public final void setnombre(java.lang.String nombre)
	{
		setnombre(getContext(), nombre);
	}

	/**
	 * Set value of nombre
	 * @param context
	 * @param nombre
	 */
	public final void setnombre(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nombre)
	{
		getMendixObject().setValue(context, MemberNames.nombre.toString(), nombre);
	}

	/**
	 * @return value of personal
	 */
	public final java.lang.Long getpersonal()
	{
		return getpersonal(getContext());
	}

	/**
	 * @param context
	 * @return value of personal
	 */
	public final java.lang.Long getpersonal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.personal.toString());
	}

	/**
	 * Set value of personal
	 * @param personal
	 */
	public final void setpersonal(java.lang.Long personal)
	{
		setpersonal(getContext(), personal);
	}

	/**
	 * Set value of personal
	 * @param context
	 * @param personal
	 */
	public final void setpersonal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long personal)
	{
		getMendixObject().setValue(context, MemberNames.personal.toString(), personal);
	}

	/**
	 * @return value of actividad
	 */
	public final java.lang.String getactividad()
	{
		return getactividad(getContext());
	}

	/**
	 * @param context
	 * @return value of actividad
	 */
	public final java.lang.String getactividad(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.actividad.toString());
	}

	/**
	 * Set value of actividad
	 * @param actividad
	 */
	public final void setactividad(java.lang.String actividad)
	{
		setactividad(getContext(), actividad);
	}

	/**
	 * Set value of actividad
	 * @param context
	 * @param actividad
	 */
	public final void setactividad(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String actividad)
	{
		getMendixObject().setValue(context, MemberNames.actividad.toString(), actividad);
	}

	/**
	 * @return value of promDeVentasAnual
	 */
	public final java.lang.Long getpromDeVentasAnual()
	{
		return getpromDeVentasAnual(getContext());
	}

	/**
	 * @param context
	 * @return value of promDeVentasAnual
	 */
	public final java.lang.Long getpromDeVentasAnual(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.promDeVentasAnual.toString());
	}

	/**
	 * Set value of promDeVentasAnual
	 * @param promdeventasanual
	 */
	public final void setpromDeVentasAnual(java.lang.Long promdeventasanual)
	{
		setpromDeVentasAnual(getContext(), promdeventasanual);
	}

	/**
	 * Set value of promDeVentasAnual
	 * @param context
	 * @param promdeventasanual
	 */
	public final void setpromDeVentasAnual(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long promdeventasanual)
	{
		getMendixObject().setValue(context, MemberNames.promDeVentasAnual.toString(), promdeventasanual);
	}

	/**
	 * @return value of tipoEmpresa
	 */
	public final java.lang.String gettipoEmpresa()
	{
		return gettipoEmpresa(getContext());
	}

	/**
	 * @param context
	 * @return value of tipoEmpresa
	 */
	public final java.lang.String gettipoEmpresa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.tipoEmpresa.toString());
	}

	/**
	 * Set value of tipoEmpresa
	 * @param tipoempresa
	 */
	public final void settipoEmpresa(java.lang.String tipoempresa)
	{
		settipoEmpresa(getContext(), tipoempresa);
	}

	/**
	 * Set value of tipoEmpresa
	 * @param context
	 * @param tipoempresa
	 */
	public final void settipoEmpresa(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tipoempresa)
	{
		getMendixObject().setValue(context, MemberNames.tipoEmpresa.toString(), tipoempresa);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return empresaMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Empresa that = (myfirstmodule.proxies.Empresa) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Empresa";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
