// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class EntidadJuridica
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject entidadJuridicaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.EntidadJuridica";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		id_entidadJuridica("id_entidadJuridica"),
		nombre("nombre"),
		razonSocial("razonSocial"),
		CUIT("CUIT"),
		CodInscripcionIGJ("CodInscripcionIGJ"),
		direccion("direccion");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EntidadJuridica(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.EntidadJuridica"));
	}

	protected EntidadJuridica(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject entidadJuridicaMendixObject)
	{
		if (entidadJuridicaMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.EntidadJuridica", entidadJuridicaMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.EntidadJuridica");

		this.entidadJuridicaMendixObject = entidadJuridicaMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EntidadJuridica.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.EntidadJuridica initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.EntidadJuridica.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.EntidadJuridica initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.EntidadJuridica(context, mendixObject);
	}

	public static myfirstmodule.proxies.EntidadJuridica load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.EntidadJuridica.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.EntidadJuridica> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.EntidadJuridica> result = new java.util.ArrayList<myfirstmodule.proxies.EntidadJuridica>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.EntidadJuridica" + xpathConstraint))
			result.add(myfirstmodule.proxies.EntidadJuridica.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of id_entidadJuridica
	 */
	public final java.lang.Long getid_entidadJuridica()
	{
		return getid_entidadJuridica(getContext());
	}

	/**
	 * @param context
	 * @return value of id_entidadJuridica
	 */
	public final java.lang.Long getid_entidadJuridica(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.id_entidadJuridica.toString());
	}

	/**
	 * Set value of id_entidadJuridica
	 * @param id_entidadjuridica
	 */
	public final void setid_entidadJuridica(java.lang.Long id_entidadjuridica)
	{
		setid_entidadJuridica(getContext(), id_entidadjuridica);
	}

	/**
	 * Set value of id_entidadJuridica
	 * @param context
	 * @param id_entidadjuridica
	 */
	public final void setid_entidadJuridica(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long id_entidadjuridica)
	{
		getMendixObject().setValue(context, MemberNames.id_entidadJuridica.toString(), id_entidadjuridica);
	}

	/**
	 * @return value of nombre
	 */
	public final java.lang.String getnombre()
	{
		return getnombre(getContext());
	}

	/**
	 * @param context
	 * @return value of nombre
	 */
	public final java.lang.String getnombre(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nombre.toString());
	}

	/**
	 * Set value of nombre
	 * @param nombre
	 */
	public final void setnombre(java.lang.String nombre)
	{
		setnombre(getContext(), nombre);
	}

	/**
	 * Set value of nombre
	 * @param context
	 * @param nombre
	 */
	public final void setnombre(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nombre)
	{
		getMendixObject().setValue(context, MemberNames.nombre.toString(), nombre);
	}

	/**
	 * @return value of razonSocial
	 */
	public final java.lang.String getrazonSocial()
	{
		return getrazonSocial(getContext());
	}

	/**
	 * @param context
	 * @return value of razonSocial
	 */
	public final java.lang.String getrazonSocial(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.razonSocial.toString());
	}

	/**
	 * Set value of razonSocial
	 * @param razonsocial
	 */
	public final void setrazonSocial(java.lang.String razonsocial)
	{
		setrazonSocial(getContext(), razonsocial);
	}

	/**
	 * Set value of razonSocial
	 * @param context
	 * @param razonsocial
	 */
	public final void setrazonSocial(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String razonsocial)
	{
		getMendixObject().setValue(context, MemberNames.razonSocial.toString(), razonsocial);
	}

	/**
	 * @return value of CUIT
	 */
	public final java.lang.String getCUIT()
	{
		return getCUIT(getContext());
	}

	/**
	 * @param context
	 * @return value of CUIT
	 */
	public final java.lang.String getCUIT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CUIT.toString());
	}

	/**
	 * Set value of CUIT
	 * @param cuit
	 */
	public final void setCUIT(java.lang.String cuit)
	{
		setCUIT(getContext(), cuit);
	}

	/**
	 * Set value of CUIT
	 * @param context
	 * @param cuit
	 */
	public final void setCUIT(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cuit)
	{
		getMendixObject().setValue(context, MemberNames.CUIT.toString(), cuit);
	}

	/**
	 * @return value of CodInscripcionIGJ
	 */
	public final java.lang.Long getCodInscripcionIGJ()
	{
		return getCodInscripcionIGJ(getContext());
	}

	/**
	 * @param context
	 * @return value of CodInscripcionIGJ
	 */
	public final java.lang.Long getCodInscripcionIGJ(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.CodInscripcionIGJ.toString());
	}

	/**
	 * Set value of CodInscripcionIGJ
	 * @param codinscripcionigj
	 */
	public final void setCodInscripcionIGJ(java.lang.Long codinscripcionigj)
	{
		setCodInscripcionIGJ(getContext(), codinscripcionigj);
	}

	/**
	 * Set value of CodInscripcionIGJ
	 * @param context
	 * @param codinscripcionigj
	 */
	public final void setCodInscripcionIGJ(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long codinscripcionigj)
	{
		getMendixObject().setValue(context, MemberNames.CodInscripcionIGJ.toString(), codinscripcionigj);
	}

	/**
	 * @return value of direccion
	 */
	public final java.lang.String getdireccion()
	{
		return getdireccion(getContext());
	}

	/**
	 * @param context
	 * @return value of direccion
	 */
	public final java.lang.String getdireccion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.direccion.toString());
	}

	/**
	 * Set value of direccion
	 * @param direccion
	 */
	public final void setdireccion(java.lang.String direccion)
	{
		setdireccion(getContext(), direccion);
	}

	/**
	 * Set value of direccion
	 * @param context
	 * @param direccion
	 */
	public final void setdireccion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String direccion)
	{
		getMendixObject().setValue(context, MemberNames.direccion.toString(), direccion);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return entidadJuridicaMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.EntidadJuridica that = (myfirstmodule.proxies.EntidadJuridica) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.EntidadJuridica";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
