// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Ingreso
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ingresoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Ingreso";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		id_ingreso("id_ingreso"),
		descripcion("descripcion"),
		montoReal("montoReal");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Ingreso(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Ingreso"));
	}

	protected Ingreso(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ingresoMendixObject)
	{
		if (ingresoMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Ingreso", ingresoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Ingreso");

		this.ingresoMendixObject = ingresoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Ingreso.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Ingreso initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Ingreso.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Ingreso initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Ingreso(context, mendixObject);
	}

	public static myfirstmodule.proxies.Ingreso load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Ingreso.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Ingreso> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Ingreso> result = new java.util.ArrayList<myfirstmodule.proxies.Ingreso>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Ingreso" + xpathConstraint))
			result.add(myfirstmodule.proxies.Ingreso.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of id_ingreso
	 */
	public final java.lang.Long getid_ingreso()
	{
		return getid_ingreso(getContext());
	}

	/**
	 * @param context
	 * @return value of id_ingreso
	 */
	public final java.lang.Long getid_ingreso(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.id_ingreso.toString());
	}

	/**
	 * Set value of id_ingreso
	 * @param id_ingreso
	 */
	public final void setid_ingreso(java.lang.Long id_ingreso)
	{
		setid_ingreso(getContext(), id_ingreso);
	}

	/**
	 * Set value of id_ingreso
	 * @param context
	 * @param id_ingreso
	 */
	public final void setid_ingreso(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long id_ingreso)
	{
		getMendixObject().setValue(context, MemberNames.id_ingreso.toString(), id_ingreso);
	}

	/**
	 * @return value of descripcion
	 */
	public final java.lang.String getdescripcion()
	{
		return getdescripcion(getContext());
	}

	/**
	 * @param context
	 * @return value of descripcion
	 */
	public final java.lang.String getdescripcion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.descripcion.toString());
	}

	/**
	 * Set value of descripcion
	 * @param descripcion
	 */
	public final void setdescripcion(java.lang.String descripcion)
	{
		setdescripcion(getContext(), descripcion);
	}

	/**
	 * Set value of descripcion
	 * @param context
	 * @param descripcion
	 */
	public final void setdescripcion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String descripcion)
	{
		getMendixObject().setValue(context, MemberNames.descripcion.toString(), descripcion);
	}

	/**
	 * @return value of montoReal
	 */
	public final java.math.BigDecimal getmontoReal()
	{
		return getmontoReal(getContext());
	}

	/**
	 * @param context
	 * @return value of montoReal
	 */
	public final java.math.BigDecimal getmontoReal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.montoReal.toString());
	}

	/**
	 * Set value of montoReal
	 * @param montoreal
	 */
	public final void setmontoReal(java.math.BigDecimal montoreal)
	{
		setmontoReal(getContext(), montoreal);
	}

	/**
	 * Set value of montoReal
	 * @param context
	 * @param montoreal
	 */
	public final void setmontoReal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal montoreal)
	{
		getMendixObject().setValue(context, MemberNames.montoReal.toString(), montoreal);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ingresoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Ingreso that = (myfirstmodule.proxies.Ingreso) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Ingreso";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
