// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Item
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject itemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Item";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		id_item("id_item"),
		detalle("detalle"),
		descripcion("descripcion"),
		valor("valor");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Item(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Item"));
	}

	protected Item(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject itemMendixObject)
	{
		if (itemMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Item", itemMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Item");

		this.itemMendixObject = itemMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Item.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Item initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Item.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Item initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Item(context, mendixObject);
	}

	public static myfirstmodule.proxies.Item load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Item.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Item> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Item> result = new java.util.ArrayList<myfirstmodule.proxies.Item>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Item" + xpathConstraint))
			result.add(myfirstmodule.proxies.Item.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of id_item
	 */
	public final java.lang.Long getid_item()
	{
		return getid_item(getContext());
	}

	/**
	 * @param context
	 * @return value of id_item
	 */
	public final java.lang.Long getid_item(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.id_item.toString());
	}

	/**
	 * Set value of id_item
	 * @param id_item
	 */
	public final void setid_item(java.lang.Long id_item)
	{
		setid_item(getContext(), id_item);
	}

	/**
	 * Set value of id_item
	 * @param context
	 * @param id_item
	 */
	public final void setid_item(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long id_item)
	{
		getMendixObject().setValue(context, MemberNames.id_item.toString(), id_item);
	}

	/**
	 * @return value of detalle
	 */
	public final java.lang.String getdetalle()
	{
		return getdetalle(getContext());
	}

	/**
	 * @param context
	 * @return value of detalle
	 */
	public final java.lang.String getdetalle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.detalle.toString());
	}

	/**
	 * Set value of detalle
	 * @param detalle
	 */
	public final void setdetalle(java.lang.String detalle)
	{
		setdetalle(getContext(), detalle);
	}

	/**
	 * Set value of detalle
	 * @param context
	 * @param detalle
	 */
	public final void setdetalle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String detalle)
	{
		getMendixObject().setValue(context, MemberNames.detalle.toString(), detalle);
	}

	/**
	 * @return value of descripcion
	 */
	public final java.lang.String getdescripcion()
	{
		return getdescripcion(getContext());
	}

	/**
	 * @param context
	 * @return value of descripcion
	 */
	public final java.lang.String getdescripcion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.descripcion.toString());
	}

	/**
	 * Set value of descripcion
	 * @param descripcion
	 */
	public final void setdescripcion(java.lang.String descripcion)
	{
		setdescripcion(getContext(), descripcion);
	}

	/**
	 * Set value of descripcion
	 * @param context
	 * @param descripcion
	 */
	public final void setdescripcion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String descripcion)
	{
		getMendixObject().setValue(context, MemberNames.descripcion.toString(), descripcion);
	}

	/**
	 * @return value of valor
	 */
	public final java.math.BigDecimal getvalor()
	{
		return getvalor(getContext());
	}

	/**
	 * @param context
	 * @return value of valor
	 */
	public final java.math.BigDecimal getvalor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.valor.toString());
	}

	/**
	 * Set value of valor
	 * @param valor
	 */
	public final void setvalor(java.math.BigDecimal valor)
	{
		setvalor(getContext(), valor);
	}

	/**
	 * Set value of valor
	 * @param context
	 * @param valor
	 */
	public final void setvalor(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal valor)
	{
		getMendixObject().setValue(context, MemberNames.valor.toString(), valor);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return itemMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Item that = (myfirstmodule.proxies.Item) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Item";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
