// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class MedioDePago
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject medioDePagoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.MedioDePago";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		id_medioDePago("id_medioDePago"),
		descripcion("descripcion"),
		numero("numero");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MedioDePago(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.MedioDePago"));
	}

	protected MedioDePago(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject medioDePagoMendixObject)
	{
		if (medioDePagoMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.MedioDePago", medioDePagoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.MedioDePago");

		this.medioDePagoMendixObject = medioDePagoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MedioDePago.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.MedioDePago initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.MedioDePago.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.MedioDePago initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.MedioDePago(context, mendixObject);
	}

	public static myfirstmodule.proxies.MedioDePago load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.MedioDePago.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.MedioDePago> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.MedioDePago> result = new java.util.ArrayList<myfirstmodule.proxies.MedioDePago>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.MedioDePago" + xpathConstraint))
			result.add(myfirstmodule.proxies.MedioDePago.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of id_medioDePago
	 */
	public final java.lang.Long getid_medioDePago()
	{
		return getid_medioDePago(getContext());
	}

	/**
	 * @param context
	 * @return value of id_medioDePago
	 */
	public final java.lang.Long getid_medioDePago(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.id_medioDePago.toString());
	}

	/**
	 * Set value of id_medioDePago
	 * @param id_mediodepago
	 */
	public final void setid_medioDePago(java.lang.Long id_mediodepago)
	{
		setid_medioDePago(getContext(), id_mediodepago);
	}

	/**
	 * Set value of id_medioDePago
	 * @param context
	 * @param id_mediodepago
	 */
	public final void setid_medioDePago(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long id_mediodepago)
	{
		getMendixObject().setValue(context, MemberNames.id_medioDePago.toString(), id_mediodepago);
	}

	/**
	 * @return value of descripcion
	 */
	public final java.lang.String getdescripcion()
	{
		return getdescripcion(getContext());
	}

	/**
	 * @param context
	 * @return value of descripcion
	 */
	public final java.lang.String getdescripcion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.descripcion.toString());
	}

	/**
	 * Set value of descripcion
	 * @param descripcion
	 */
	public final void setdescripcion(java.lang.String descripcion)
	{
		setdescripcion(getContext(), descripcion);
	}

	/**
	 * Set value of descripcion
	 * @param context
	 * @param descripcion
	 */
	public final void setdescripcion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String descripcion)
	{
		getMendixObject().setValue(context, MemberNames.descripcion.toString(), descripcion);
	}

	/**
	 * @return value of numero
	 */
	public final java.lang.Long getnumero()
	{
		return getnumero(getContext());
	}

	/**
	 * @param context
	 * @return value of numero
	 */
	public final java.lang.Long getnumero(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.numero.toString());
	}

	/**
	 * Set value of numero
	 * @param numero
	 */
	public final void setnumero(java.lang.Long numero)
	{
		setnumero(getContext(), numero);
	}

	/**
	 * Set value of numero
	 * @param context
	 * @param numero
	 */
	public final void setnumero(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long numero)
	{
		getMendixObject().setValue(context, MemberNames.numero.toString(), numero);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return medioDePagoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.MedioDePago that = (myfirstmodule.proxies.MedioDePago) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.MedioDePago";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
